#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeshNetwork

#include "Basic.hpp"

#include "ReplicationGraph_classes.hpp"
#include "OnlineSubsystemUtils_classes.hpp"
#include "MeshNetwork_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class MeshNetwork.MeshBeaconClient
// 0x0038 (0x03E0 - 0x03A8)
class AMeshBeaconClient : public AOnlineBeaconClient
{
public:
	uint8                                         Pad_3A8[0x20];                                     // 0x03A8(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bConnectedToRoot;                                  // 0x03C8(0x0001)(Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3C9[0x17];                                     // 0x03C9(0x0017)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_ConnectedToRoot();
	void ServerUpdateLevelVisibility(class FName PackageName, bool bIsVisible);
	void ServerUpdateMultipleLevelsVisibility(const TArray<struct FUpdateLevelVisibilityLevelInfo>& LevelVisibilities);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshBeaconClient")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshBeaconClient")
	}
	static class AMeshBeaconClient* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMeshBeaconClient>();
	}
};
DUMPER7_ASSERTS_AMeshBeaconClient;

// Class MeshNetwork.MeshBeaconHost
// 0x0008 (0x0418 - 0x0410)
class AMeshBeaconHost : public AOnlineBeaconHost
{
public:
	int32                                         MaxConnections;                                    // 0x0410(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_414[0x4];                                      // 0x0414(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshBeaconHost")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshBeaconHost")
	}
	static class AMeshBeaconHost* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMeshBeaconHost>();
	}
};
DUMPER7_ASSERTS_AMeshBeaconHost;

// Class MeshNetwork.MeshReplicationGraph
// 0x0008 (0x0490 - 0x0488)
class UMeshReplicationGraph : public UReplicationGraph
{
public:
	class UReplicationGraphNode_ActorList*        AlwaysRelevantNode;                                // 0x0488(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshReplicationGraph")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshReplicationGraph")
	}
	static class UMeshReplicationGraph* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMeshReplicationGraph>();
	}
};
DUMPER7_ASSERTS_UMeshReplicationGraph;

// Class MeshNetwork.MeshBeaconHostObject
// 0x0008 (0x0358 - 0x0350)
class AMeshBeaconHostObject : public AOnlineBeaconHostObject
{
public:
	uint8                                         Pad_350[0x8];                                      // 0x0350(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshBeaconHostObject")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshBeaconHostObject")
	}
	static class AMeshBeaconHostObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMeshBeaconHostObject>();
	}
};
DUMPER7_ASSERTS_AMeshBeaconHostObject;

// Class MeshNetwork.MeshConnection
// 0x0000 (0x1988 - 0x1988)
class UMeshConnection final : public UIpConnection
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshConnection")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshConnection")
	}
	static class UMeshConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMeshConnection>();
	}
};
DUMPER7_ASSERTS_UMeshConnection;

// Class MeshNetwork.MeshNetDriver
// 0x0000 (0x0768 - 0x0768)
class UMeshNetDriver final : public UIpNetDriver
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshNetDriver")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshNetDriver")
	}
	static class UMeshNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMeshNetDriver>();
	}
};
DUMPER7_ASSERTS_UMeshNetDriver;

// Class MeshNetwork.MeshNetworkComponent
// 0x00A8 (0x01A0 - 0x00F8)
class UMeshNetworkComponent final : public UActorComponent
{
public:
	EMeshNetworkRelevancy                         MeshRelevancy;                                     // 0x00F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, double>                     AggregationTimeouts;                               // 0x0100(0x0050)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	TMap<class FName, struct FAggregatedFunction> AggregatedFunctions;                               // 0x0150(0x0050)(ZeroConstructor, Transient, Protected, NativeAccessSpecifierProtected)

public:
	EMeshNetworkNodeType GetMeshNetworkNodeType() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshNetworkComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshNetworkComponent")
	}
	static class UMeshNetworkComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMeshNetworkComponent>();
	}
};
DUMPER7_ASSERTS_UMeshNetworkComponent;

// Class MeshNetwork.MeshNetworkSubsystem
// 0x0018 (0x0040 - 0x0028)
class UMeshNetworkSubsystem final : public UGameInstanceSubsystem
{
public:
	UMulticastDelegateProperty_                   OnConnectedToRootChanged;                          // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	EMeshNetworkNodeType                          NodeType;                                          // 0x0038(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bConnectedToRoot;                                  // 0x0039(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool GetConnectedToRoot() const;
	EMeshNetworkNodeType GetMeshNetworkNodeType() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MeshNetworkSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MeshNetworkSubsystem")
	}
	static class UMeshNetworkSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMeshNetworkSubsystem>();
	}
};
DUMPER7_ASSERTS_UMeshNetworkSubsystem;

}

