#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeshNetwork

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MeshNetwork_structs.hpp"


namespace SDK::Params
{

// Function MeshNetwork.MeshBeaconClient.ServerUpdateLevelVisibility
// 0x0010 (0x0010 - 0x0000)
struct MeshBeaconClient_ServerUpdateLevelVisibility final
{
public:
	class FName                                   PackageName;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsVisible;                                        // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MeshBeaconClient_ServerUpdateLevelVisibility;

// Function MeshNetwork.MeshBeaconClient.ServerUpdateMultipleLevelsVisibility
// 0x0010 (0x0010 - 0x0000)
struct MeshBeaconClient_ServerUpdateMultipleLevelsVisibility final
{
public:
	TArray<struct FUpdateLevelVisibilityLevelInfo> LevelVisibilities;                                // 0x0000(0x0010)(ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MeshBeaconClient_ServerUpdateMultipleLevelsVisibility;

// Function MeshNetwork.MeshNetworkComponent.GetMeshNetworkNodeType
// 0x0001 (0x0001 - 0x0000)
struct MeshNetworkComponent_GetMeshNetworkNodeType final
{
public:
	EMeshNetworkNodeType                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MeshNetworkComponent_GetMeshNetworkNodeType;

// Function MeshNetwork.MeshNetworkSubsystem.GetConnectedToRoot
// 0x0001 (0x0001 - 0x0000)
struct MeshNetworkSubsystem_GetConnectedToRoot final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MeshNetworkSubsystem_GetConnectedToRoot;

// Function MeshNetwork.MeshNetworkSubsystem.GetMeshNetworkNodeType
// 0x0001 (0x0001 - 0x0000)
struct MeshNetworkSubsystem_GetMeshNetworkNodeType final
{
public:
	EMeshNetworkNodeType                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MeshNetworkSubsystem_GetMeshNetworkNodeType;

}

