#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Party

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// Enum Party.EApprovalAction
// NumValues: 0x0005
enum class EApprovalAction : uint8
{
	Approve                                  = 0,
	Enqueue                                  = 1,
	EnqueueAndStartBeacon                    = 2,
	Deny                                     = 3,
	EApprovalAction_MAX                      = 4,
};

// Enum Party.EPartyJoinDenialReason
// NumValues: 0x0040
enum class EPartyJoinDenialReason : uint8
{
	NoReason                                 = 0,
	JoinAttemptAborted                       = 1,
	Busy                                     = 2,
	OssUnavailable                           = 3,
	PartyFull                                = 4,
	GameFull                                 = 5,
	NotPartyLeader                           = 6,
	PartyPrivate                             = 7,
	JoinerCrossplayRestricted                = 8,
	MemberCrossplayRestricted                = 9,
	GameModeRestricted                       = 10,
	Banned                                   = 11,
	NotLoggedIn                              = 12,
	CheckingForRejoin                        = 13,
	TargetUserMissingPresence                = 14,
	TargetUserUnjoinable                     = 15,
	AlreadyLeaderInPlatformSession           = 16,
	TargetUserPlayingDifferentGame           = 17,
	TargetUserMissingPlatformSession         = 18,
	PlatformSessionMissingJoinInfo           = 19,
	FailedToStartFindConsoleSession          = 20,
	MissingPartyClassForTypeId               = 21,
	TargetUserBlocked                        = 22,
	CustomReason0                            = 23,
	CustomReason1                            = 24,
	CustomReason2                            = 25,
	CustomReason3                            = 26,
	CustomReason4                            = 27,
	CustomReason5                            = 28,
	CustomReason6                            = 29,
	CustomReason7                            = 30,
	CustomReason8                            = 31,
	CustomReason9                            = 32,
	CustomReason10                           = 33,
	CustomReason11                           = 34,
	CustomReason12                           = 35,
	CustomReason13                           = 36,
	CustomReason14                           = 37,
	CustomReason15                           = 38,
	CustomReason16                           = 39,
	CustomReason17                           = 40,
	CustomReason18                           = 41,
	CustomReason19                           = 42,
	CustomReason20                           = 43,
	CustomReason21                           = 44,
	CustomReason22                           = 45,
	CustomReason23                           = 46,
	CustomReason24                           = 47,
	CustomReason25                           = 48,
	CustomReason26                           = 49,
	CustomReason27                           = 50,
	CustomReason28                           = 51,
	CustomReason29                           = 52,
	CustomReason30                           = 53,
	CustomReason31                           = 54,
	CustomReason32                           = 55,
	CustomReason33                           = 56,
	CustomReason34                           = 57,
	CustomReason35                           = 58,
	CustomReason36                           = 59,
	CustomReason37                           = 60,
	CustomReason38                           = 61,
	CustomReason39                           = 62,
	MAX                                      = 63,
};

// Enum Party.EPartyInviteRestriction
// NumValues: 0x0004
enum class EPartyInviteRestriction : uint8
{
	AnyMember                                = 0,
	LeaderOnly                               = 1,
	NoInvites                                = 2,
	EPartyInviteRestriction_MAX              = 3,
};

// Enum Party.EPartyType
// NumValues: 0x0004
enum class EPartyType : uint8
{
	Public                                   = 0,
	FriendsOnly                              = 1,
	Private                                  = 2,
	EPartyType_MAX                           = 3,
};

// Enum Party.ESocialChannelType
// NumValues: 0x0007
enum class ESocialChannelType : uint8
{
	General                                  = 0,
	Founder                                  = 1,
	Party                                    = 2,
	Team                                     = 3,
	System                                   = 4,
	Private                                  = 5,
	ESocialChannelType_MAX                   = 6,
};

// Enum Party.ECrossplayPreference
// NumValues: 0x0005
enum class ECrossplayPreference : uint8
{
	NoSelection                              = 0,
	OptedIn                                  = 1,
	OptedOut                                 = 2,
	OptedOutRestricted                       = 3,
	ECrossplayPreference_MAX                 = 4,
};

// Enum Party.ESocialRelationship
// NumValues: 0x0008
enum class ESocialRelationship : uint8
{
	FriendInviteReceived                     = 0,
	FriendInviteSent                         = 1,
	PartyInvite                              = 2,
	Friend                                   = 3,
	BlockedPlayer                            = 4,
	SuggestedFriend                          = 5,
	RecentPlayer                             = 6,
	ESocialRelationship_MAX                  = 7,
};

// Enum Party.ESocialSubsystem
// NumValues: 0x0003
enum class ESocialSubsystem : uint8
{
	Primary                                  = 0,
	Platform                                 = 1,
	MAX                                      = 2,
};

// ScriptStruct Party.OnlinePartyRepDataBase
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FOnlinePartyRepDataBase
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FOnlinePartyRepDataBase;

// ScriptStruct Party.PartyPrivacySettings
// 0x0003 (0x0003 - 0x0000)
struct FPartyPrivacySettings final
{
public:
	EPartyType                                    PartyType;                                         // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPartyInviteRestriction                       PartyInviteRestriction;                            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOnlyLeaderFriendsCanJoin;                         // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FPartyPrivacySettings;

// ScriptStruct Party.UserPlatform
// 0x0010 (0x0010 - 0x0000)
struct FUserPlatform final
{
public:
	class FString                                 PlatformStr;                                       // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
};
DUMPER7_ASSERTS_FUserPlatform;

// ScriptStruct Party.PartyMemberRepData
// 0x0118 (0x0130 - 0x0018)
struct FPartyMemberRepData : public FOnlinePartyRepDataBase
{
public:
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUserPlatform                          Platform;                                          // 0x0020(0x0010)(NativeAccessSpecifierPrivate)
	uint8                                         Pad_30[0x30];                                      // 0x0030(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUniqueNetIdRepl                       PlatformUniqueId;                                  // 0x0060(0x0028)(HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_88[0x30];                                      // 0x0088(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PlatformSessionId;                                 // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_C8[0x30];                                      // 0x00C8(0x0030)(Fixing Size After Last Property [ Dumper-7 ])
	ECrossplayPreference                          CrossplayPreference;                               // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_F9[0x37];                                      // 0x00F9(0x0037)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPartyMemberRepData;

// ScriptStruct Party.PartyPlatformSessionInfo
// 0x0040 (0x0040 - 0x0000)
struct FPartyPlatformSessionInfo final
{
public:
	class FName                                   OssName;                                           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SessionId;                                         // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FUniqueNetIdRepl                       OwnerPrimaryId;                                    // 0x0018(0x0028)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FPartyPlatformSessionInfo;

// ScriptStruct Party.PartyRepData
// 0x0068 (0x0080 - 0x0018)
struct FPartyRepData : public FOnlinePartyRepDataBase
{
public:
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPartyPrivacySettings                  PrivacySettings;                                   // 0x0020(0x0003)(NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_23[0x35];                                      // 0x0023(0x0035)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPartyPlatformSessionInfo>      PlatformSessions;                                  // 0x0058(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_68[0x18];                                      // 0x0068(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FPartyRepData;

// ScriptStruct Party.SocialChatChannelConfig
// 0x0040 (0x0040 - 0x0000)
struct FSocialChatChannelConfig final
{
public:
	class USocialUser*                            SocialUser;                                        // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8[0x10];                                       // 0x0008(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class USocialChatChannel*>             ListenChannels;                                    // 0x0018(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_28[0x18];                                      // 0x0028(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSocialChatChannelConfig;

}

